### PR TITLE
Adding the Lift Kata

### PR DESCRIPTION
**Pull request by soonernotfaster**
Still in progress but I wanted feedback. I'm still working on getting an image.

### CODE REVIEW

**Comment by Egga-zz** [comment]
Love it! I would like to merge it to the original repo. Let me know, when you're ready ;-)

**Comment by soonernotfaster** [comment]
Thanks, I think it’s ready.

**Comment by Egga-zz** [comment]
Awesome! Merged. I'm gonna make a few test runs soons and let you know how it went.

**Comment by soonernotfaster** [comment]
Awesome, thanks

**Comment by soonernotfaster** [comment]
Looks like I accidentally added the constraint tag to the kata. I’ll send a
new pull request to remove it

**Pull request merged**
