### PR TITLE
Refactoring + how to collaborate

### PR DESCRIPTION
**Pull request by rachelcarmena**
A friend of mine asked me how to add a new kata in this awesome initiative.

I was preparing a PR for you to add a detailed explanation when I realized about possible improvements. Here they are:

* Repository organization in order to differentiate topics, levels, constraints and katas easily:
   * Topics **moved** from the main directory to `_topics` directory.
   * Levels **moved** from the main directory to `_levels` directory.
   * Constraints **moved** from `_posts` directory to `_constraints` directory.
   * Katas **moved** from `_posts` directory to `_katas` directory (date is not needed).
* Bundle:
   * There are no longer liquid warnings when executing `bundle`.
* Web content:
   * Added instructions in README in order to know how to add a new kata.
   * Constraints no longer appear in the result when selecting katas by topic. That's the reason why I've removed `categories` tag from the corresponding files. 

With the current version, **Baby Steps** (a constraint) appears in **All Katas** list:

now

With this proposal, **Baby Steps** doesn't appear in **All Katas** list:

new-proposal

## Another example

With the current version, **Tell Don't Ask** (a constraint) appears when choosing **Mocks** topic:

now-2

With this proposal, **Tell Don't Ask** doesn't appear when choosing Mocks topic:

new-proposal-2

And this happens with all the constraints. They don't appear as katas in the results. It's the only change on the current version.

I hope it's useful for you!

### CODE REVIEW

**Comment by rachelcarmena** [comment]
poke poke :wink: 

Please, I'm waiting for this PR in order to contribute with more katas :pray: 

Thanks!

**Comment by rachelcarmena** [comment]
@Egga , @rradczewski , hi! 
I've just changed the PR description and I've added screenshots in order to explain better this proposal.
I hope it's useful for you!!

**Comment by rachelcarmena** [comment]
@Egga , @rradczewski , hi! 
I've just changed the PR description and I've added screenshots in order to explain this proposal better.
I hope it's useful for you!!

**Comment by rradczewski** [comment]
Looks good and simplifies things, thanks @rachelcarmena !

**Comment by rachelcarmena** [comment]
Oh! Thanks to you! You made me super happy! :tada:

**Pull request merged**
